#!/bin/bash
git add .
echo -n "Enter a commit message: "
read answer
git commit -m "$answer"

send "paradoxSatire"
expect "Username for 'https://github.com':"

send "F@lling2"
expect "Password for 'https://paradoxSatire@github.com':"

git push https://github.com/paradoxSatire/arcaenions
